<a href="https://colab.research.google.com/github/WBruni/Analise_Vendas_e_Desempenho_Loja/blob/main/TelecomX_BR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "Churn de Clientes" na Telecom X

O "Churn de Clientes" da Telecom X, tem como objetivo principal entender os fatores que contribuem para o alto índice de cancelamentos de clientes (churn). O objetivo aqui é coletar, tratar e analisar os dados usando o Python e suas bibliotecas.

Os insights gerados a partir desta análise serão cruciais para que a equipe de Data Science possa desenvolver modelos preditivos e estratégias eficazes para reduzir a evasão de clientes.
___

# 🔍 **Análise da Estrutura dos Dados**
Os dados são organizados em um formato hierárquico (dicionário dentro de dicionário), contendo as seguintes informações:

1. **Identificação do Cliente**  
   - `'customerID'`: Identificador único do cliente.  
   - `'Churn'`: Indica se o cliente cancelou o serviço (`Yes` ou `No`).  

2. **Informações do Cliente** (`'customer'`)  
   - `'gender'`: Gênero do cliente (`Male` ou `Female`).  
   - `'SeniorCitizen'`: Indica se o cliente é idoso (0 = Não, 1 = Sim).  
   - `'Partner'`: Se o cliente tem um parceiro(a).  
   - `'Dependents'`: Se o cliente tem dependentes.  
   - `'tenure'`: Tempo de permanência como cliente (em meses).  

3. **Serviços de Telefonia** (`'phone'`)  
   - `'PhoneService'`: Indica se o cliente possui serviço de telefone (`Yes` ou `No`).  
   - `'MultipleLines'`: Se possui múltiplas linhas telefônicas.  

4. **Serviços de Internet** (`'internet'`)  
   - Tipo de serviço de internet contratado (`DSL`, `Fiber optic`, `No`).  
   - Serviços adicionais (`OnlineSecurity`, `OnlineBackup`, `DeviceProtection`, `TechSupport`, `StreamingTV`, `StreamingMovies`).  

5. **Informações da Conta** (`'account'`)  
   - `'Contract'`: Tipo de contrato (`Month-to-month`, `One year`, `Two year`).  
   - `'PaperlessBilling'`: Se o cliente recebe faturas eletrônicas.  
   - `'PaymentMethod'`: Método de pagamento (`Bank transfer`, `Credit card`, `Electronic check`, `Mailed check`).  
   - `'Charges'`:  
     - `'Monthly'`: Valor mensal cobrado.  
     - `'Total'`: Valor total pago pelo cliente.

#📌 Extracão

In [1]:
import requests
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/WBruni/analise-churn-telecom-x/refs/heads/main/TelecomX_Data.json'
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [3]:
df = pd.json_normalize(data)
df

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

#🔧 Transformação

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

## 🔍 Verificação

### 1. Valores Únicos

In [5]:
for col in df.columns:
  print(f'{col}: {df[col].unique()}')
  if df[col].nunique() < 50:
    print(df[col].unique())
    print('-' * 50)

customerID: ['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
Churn: ['No' 'Yes' '']
['No' 'Yes' '']
--------------------------------------------------
customer.gender: ['Female' 'Male']
['Female' 'Male']
--------------------------------------------------
customer.SeniorCitizen: [0 1]
[0 1]
--------------------------------------------------
customer.Partner: ['Yes' 'No']
['Yes' 'No']
--------------------------------------------------
customer.Dependents: ['Yes' 'No']
['Yes' 'No']
--------------------------------------------------
customer.tenure: [ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
phone.PhoneService: ['Yes' 'No']
['Yes' 'No']
--------------------------------------------------
phone.MultipleLines: ['No' 'Yes' 'No phone service']
['No' 'Yes' 'No phone service']
--------------------------------------------------
internet.InternetService: ['DSL' 'Fiber optic' 'No']
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
internet.OnlineSecurity: ['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
--------------------------------------------------
internet.OnlineBackup: ['Yes' 'No' 'No internet service']
['Yes' 'No' 'No internet service']
--------------------------------------------------
internet.DeviceProtection: ['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
--------------------------------------------------
internet.TechSupport: ['Yes' 'No' 'No internet service']
['Yes' 'No' 'No internet service']
--------------------------------------------------
internet.StreamingTV: ['Yes' 'No' 'No internet service']
['Yes' 'No' 'No internet service']
--------------------------------------------------
internet.StreamingMovies: ['No' 'Yes' 'No internet service']
['No' 'Yes' 'No internet service']
--------------------------------------------------
account.Contract: ['One year' 'Month-to-month' 'Two year']
['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
account.PaperlessBilling: ['Yes' 'No']
['Yes' 'No']
--------------------------------------------------
account.PaymentMethod: ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
account.Charges.Monthly: [65.6  59.9  73.9  ... 91.75 68.8  67.85]
account.Charges.Total: ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

### 2. Valores Duplicados

In [6]:
print('Número de Valores Duplicados', df.duplicated().sum())

Número de Valores Duplicados 0

### 3. Valores Nulos

In [7]:
print('Número de Valores Nulos \n', df.isnull().sum())

Número de Valores Nulos
 customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

### 4. Valores Vazios ou em Branco

In [8]:
df.apply(lambda x: x.astype(str).str.strip() == '').sum()

customerID                     0
Churn                        224
customer.gender                0
customer.SeniorCitizen         0
customer.Partner               0
customer.Dependents            0
customer.tenure                0
phone.PhoneService             0
phone.MultipleLines            0
internet.InternetService       0
internet.OnlineSecurity        0
internet.OnlineBackup          0
internet.DeviceProtection      0
internet.TechSupport           0
internet.StreamingTV           0
internet.StreamingMovies       0
account.Contract               0
account.PaperlessBilling       0
account.PaymentMethod          0
account.Charges.Monthly        0
account.Charges.Total         11
dtype: int64

### 5. Lidando com Valores Vazios

In [9]:
df = df[df['Churn'].astype(str).str.strip() != '']
df = df[df['account.Charges.Total'].astype(str).str.strip() != '']

print(f'Número de linhas após remoção de valores vazios: {len(df)}')

# Verifique novamente os valores vazios para confirmar
print('\nVerificação de valores vazios/em branco após a remoção:')
display(df.apply(lambda x: x.astype(str).str.strip() == '').sum().to_frame(name='Qtd Valores Vazios'))

Número de linhas após remoção de valores vazios: 7032

Verificação de valores vazios/em branco após a remoção:

                           Qtd Valores Vazios
customerID                                  0
Churn                                       0
customer.gender                             0
customer.SeniorCitizen                      0
customer.Partner                            0
customer.Dependents                         0
customer.tenure                             0
phone.PhoneService                          0
phone.MultipleLines                         0
internet.InternetService                    0
internet.OnlineSecurity                     0
internet.OnlineBackup                       0
internet.DeviceProtection                   0
internet.TechSupport                        0
internet.StreamingTV                        0
internet.StreamingMovies                    0
account.Contract                            0
account.PaperlessBilling                    0
account.PaymentMethod                       0
account.Charges.Monthly                     0
account.Charges.Total                       0

### 6. Conversão de `account.Charges.Total` para `float`

In [10]:
df['account.Charges.Total'] = pd.to_numeric(df['account.Charges.Total'])


print('Tipo de dado da coluna account.Charges.Total após conversão:')
df.info()

Tipo de dado da coluna account.Charges.Total após conversão:
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   object
 2   customer.gender            7032 non-null   object
 3   customer.SeniorCitizen     7032 non-null   int64
 4   customer.Partner           7032 non-null   object
 5   customer.Dependents        7032 non-null   object
 6   customer.tenure            7032 non-null   int64
 7   phone.PhoneService         7032 non-null   object
 8   phone.MultipleLines        7032 non-null   object
 9   internet.InternetService   7032 non-null   object
 10  internet.OnlineSecurity    7032 non-null   object
 11  internet.OnlineBackup      7032 non-null   object
 12  internet.DeviceProtection  7032 non-null   object
 13  internet.TechSupport       7032 non-null   object
 14  internet.StreamingTV       7032 non-null   object
 15  internet.StreamingMovies   7032 non-null   object
 16  account.Contract           7032 non-null   object
 17  account.PaperlessBilling   7032 non-null   object
 18  account.PaymentMethod      7032 non-null   object
 19  account.Charges.Monthly    7032 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

##🔧 Transformação

### 1. Binarização de Múltiplas Colunas no `df`

In [11]:
# Mapeamento comum para colunas 'Yes'/'No'
binary_mapping = {
    'No': 0,
    'Yes': 1
}

# Lista de colunas a serem binarizadas, incluindo 'Churn'
columns_to_binarize = [
    'Churn',
    'customer.Partner',
    'customer.Dependents',
    'phone.PhoneService',
    'account.PaperlessBilling'
]

for col in columns_to_binarize:
    if col in df.columns:
        df[col] = df[col].map(binary_mapping)
        print(f"Coluna '{col}' binarizada. Valores únicos: {df[col].unique()}")
    else:
        print(f"Coluna '{col}' não encontrada no DataFrame.")


print("\nVerificando os tipos de dados após a binarização combinada:")
df.info()

Coluna 'Churn' binarizada. Valores únicos: [0 1]
Coluna 'customer.Partner' binarizada. Valores únicos: [1 0]
Coluna 'customer.Dependents' binarizada. Valores únicos: [1 0]
Coluna 'phone.PhoneService' binarizada. Valores únicos: [1 0]
Coluna 'account.PaperlessBilling' binarizada. Valores únicos: [1 0]

Verificando os tipos de dados após a binarização combinada:
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   int64
 2   customer.gender            7032 non-null   object
 3   customer.SeniorCitizen     7032 non-null   int64
 4   customer.Partner           7032 non-null   int64
 5   customer.Dependents        7032 non-null   int64
 6   customer.tenure            7032 non-null   int64
 7   phone.PhoneService         7032 non-null   int64
 8   phone.MultipleLines        7032 non-null   object
 9   internet.InternetService   7032 non-null   object
 10  internet.OnlineSecurity    7032 non-null   object
 11  internet.OnlineBackup      7032 non-null   object
 12  internet.DeviceProtection  7032 non-null   object
 13  internet.TechSupport       7032 non-null   object
 14  internet.StreamingTV       7032 non-null   object
 15  internet.StreamingMovies   7032 non-null   object
 16  account.Contract           7032 non-null   object
 17  account.PaperlessBilling   7032 non-null   int64
 18  account.PaymentMethod      7032 non-null   object
 19  account.Charges.Monthly    7032 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(7), object(12)
memory usage: 1.2+ MB

### 2. Binarização da Coluna `customer.gender` no `df`

In [12]:
# Mapeamento para binarizar a coluna 'customer.gender'
# Vamos atribuir 0 para 'Female' e 1 para 'Male'
binary_gender_mapping = {
    'Female': 0,
    'Male': 1
}

# Aplica o mapeamento à coluna 'customer.gender' no df
df['customer.gender'] = df['customer.gender'].map(binary_gender_mapping)

print("Coluna 'customer.gender' após a binarização:")
display(df[['customer.gender']].head())

print("Verificando os tipos de dados após a binarização:")
df.info()

Coluna 'customer.gender' após a binarização:

   customer.gender
0                0
1                1
2                1
3                1
4                0

Verificando os tipos de dados após a binarização:
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7032 non-null   object
 1   Churn                      7032 non-null   int64
 2   customer.gender            7032 non-null   int64
 3   customer.SeniorCitizen     7032 non-null   int64
 4   customer.Partner           7032 non-null   int64
 5   customer.Dependents        7032 non-null   int64
 6   customer.tenure            7032 non-null   int64
 7   phone.PhoneService         7032 non-null   int64
 8   phone.MultipleLines        7032 non-null   object
 9   internet.InternetService   7032 non-null   object
 10  internet.OnlineSecurity    7032 non-null   object
 11  internet.OnlineBackup      7032 non-null   object
 12  internet.DeviceProtection  7032 non-null   object
 13  internet.TechSupport       7032 non-null   object
 14  internet.StreamingTV       7032 non-null   object
 15  internet.StreamingMovies   7032 non-null   object
 16  account.Contract           7032 non-null   object
 17  account.PaperlessBilling   7032 non-null   int64
 18  account.PaymentMethod      7032 non-null   object
 19  account.Charges.Monthly    7032 non-null   float64
 20  account.Charges.Total      7032 non-null   float64
dtypes: float64(2), int64(8), object(11)
memory usage: 1.2+ MB

### 3. One-Hot Encoding das Colunas Categóricas no `df`

In [13]:
# Lista de colunas para aplicar One-Hot Encoding
columns_to_onehot = [
    'phone.MultipleLines',
    'internet.InternetService',
    'internet.OnlineSecurity',
    'internet.OnlineBackup',
    'internet.DeviceProtection',
    'internet.TechSupport',
    'internet.StreamingTV',
    'internet.StreamingMovies',
    'account.Contract',
    'account.PaymentMethod'
]

# Aplica One-Hot Encoding e concatena com o DataFrame original
# Usamos drop_first=True para evitar a multicolinearidade (cria N-1 colunas para N categorias)
df = pd.get_dummies(df, columns=columns_to_onehot, drop_first=True)

print("DataFrame após One-Hot Encoding. Verifique as novas colunas:")
display(df.head())

print("\nVerificando os tipos de dados após o One-Hot Encoding:")
df.info()

DataFrame após One-Hot Encoding. Verifique as novas colunas:

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,account.PaperlessBilling,account.Charges.Monthly,...,internet.TechSupport_Yes,internet.StreamingTV_No internet service,internet.StreamingTV_Yes,internet.StreamingMovies_No internet service,internet.StreamingMovies_Yes,account.Contract_One year,account.Contract_Two year,account.PaymentMethod_Credit card (automatic),account.PaymentMethod_Electronic check,account.PaymentMethod_Mailed check
0,0002-ORFBO,0,0,0,1,1,9,1,1,65.6,...,True,False,True,False,False,True,False,False,False,True
1,0003-MKNFE,0,1,0,0,0,9,1,0,59.9,...,False,False,False,False,True,False,False,False,False,True
2,0004-TLHLJ,1,1,0,0,0,4,1,1,73.9,...,False,False,False,False,False,False,False,False,True,False
3,0011-IGKFF,1,1,1,1,0,13,1,1,98.0,...,False,False,True,False,True,False,False,False,True,False
4,0013-EXCHZ,1,0,1,1,0,3,1,1,83.9,...,True,False,True,False,False,False,False,False,False,True

Verificando os tipos de dados após o One-Hot Encoding:
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 32 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   customerID                                     7032 non-null   object
 1   Churn                                          7032 non-null   int64
 2   customer.gender                                7032 non-null   int64
 3   customer.SeniorCitizen                         7032 non-null   int64
 4   customer.Partner                               7032 non-null   int64
 5   customer.Dependents                            7032 non-null   int64
 6   customer.tenure                                7032 non-null   int64
 7   phone.PhoneService                             7032 non-null   int64
 8   account.PaperlessBilling                       7032 non-null   int64
 9   account.Charges.Monthly                        7032 non-null   float64
 10  account.Charges.Total                          7032 non-null   float64
 11  phone.MultipleLines_No phone service           7032 non-null   bool
 12  phone.MultipleLines_Yes                        7032 non-null   bool
 13  internet.InternetService_Fiber optic           7032 non-null   bool
 14  internet.InternetService_No                    7032 non-null   bool
 15  internet.OnlineSecurity_No internet service    7032 non-null   bool
 16  internet.OnlineSecurity_Yes                    7032 non-null   bool
 17  internet.OnlineBackup_No internet service      7032 non-null   bool
 18  internet.OnlineBackup_Yes                      7032 non-null   bool
 19  internet.DeviceProtection_No internet service  7032 non-null   bool
 20  internet.DeviceProtection_Yes                  7032 non-null   bool
 21  internet.TechSupport_No internet service       7032 non-null   bool
 22  internet.TechSupport_Yes                       7032 non-null   bool
 23  internet.StreamingTV_No internet service       7032 non-null   bool
 24  internet.StreamingTV_Yes                       7032 non-null   bool
 25  internet.StreamingMovies_No internet service   7032 non-null   bool
 26  internet.StreamingMovies_Yes                   7032 non-null   bool
 27  account.Contract_One year                      7032 non-null   bool
 28  account.Contract_Two year                      7032 non-null   bool
 29  account.PaymentMethod_Credit card (automatic)  7032 non-null   bool
 30  account.PaymentMethod_Electronic check         7032 non-null   bool
 31  account.PaymentMethod_Mailed check             7032 non-null   bool
dtypes: bool(21), float64(2), int64(8), object(1)
memory usage: 803.5+ KB

### 4. Criando Cópia do `df`

In [22]:
df_ml = df.copy()

### 5. Tradução dos Nomes das Colunas

In [23]:
# Dicionário para traduzir os nomes das colunas
col_translation_dict = {
    'customerID': 'id_cliente',
    'Churn': 'churn',
    'customer.gender': 'genero_cliente',
    'customer.SeniorCitizen': 'cliente_senior',
    'customer.Partner': 'tem_parceiro',
    'customer.Dependents': 'tem_dependentes',
    'customer.tenure': 'meses_servico',
    'phone.PhoneService': 'servico_telefone',
    'account.PaperlessBilling': 'fatura_digital',
    'account.Charges.Monthly': 'cobranca_mensal',
    'account.Charges.Total': 'cobranca_total',
    'phone.MultipleLines_No phone service': 'varias_linhas_sem_servico_telefone',
    'phone.MultipleLines_Yes': 'varias_linhas_sim',
    'internet.InternetService_Fiber optic': 'internet_fibra_optica',
    'internet.InternetService_No': 'internet_sem_servico',
    'internet.OnlineSecurity_No internet service': 'seguranca_online_sem_servico_internet',
    'internet.OnlineSecurity_Yes': 'seguranca_online_sim',
    'internet.OnlineBackup_No internet service': 'backup_online_sem_servico_internet',
    'internet.OnlineBackup_Yes': 'backup_online_sim',
    'internet.DeviceProtection_No internet service': 'protecao_dispositivo_sem_servico_internet',
    'internet.DeviceProtection_Yes': 'protecao_dispositivo_sim',
    'internet.TechSupport_No internet service': 'suporte_tecnico_sem_servico_internet',
    'internet.TechSupport_Yes': 'suporte_tecnico_sim',
    'internet.StreamingTV_No internet service': 'tv_streaming_sem_servico_internet',
    'internet.StreamingTV_Yes': 'tv_streaming_sim',
    'internet.StreamingMovies_No internet service': 'filmes_streaming_sem_servico_internet',
    'internet.StreamingMovies_Yes': 'filmes_streaming_sim',
    'account.Contract_One year': 'contrato_um_ano',
    'account.Contract_Two year': 'contrato_dois_anos',
    'account.PaymentMethod_Credit card (automatic)': 'metodo_pagamento_cartao_credito_automatico',
    'account.PaymentMethod_Electronic check': 'metodo_pagamento_cheque_eletronico',
    'account.PaymentMethod_Mailed check': 'metodo_pagamento_cheque_pelo_correio'
}

# Renomeia as colunas do DataFrame
df_ml = df_ml.rename(columns=col_translation_dict)

print("Nomes das colunas traduzidos no df_ml. Verifique com df_ml.info():")
df_ml.info()

Nomes das colunas traduzidos no df_ml. Verifique com df_ml.info():
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 32 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   id_cliente                                  7032 non-null   object
 1   churn                                       7032 non-null   int64
 2   genero_cliente                              7032 non-null   int64
 3   cliente_senior                              7032 non-null   int64
 4   tem_parceiro                                7032 non-null   int64
 5   tem_dependentes                             7032 non-null   int64
 6   meses_servico                               7032 non-null   int64
 7   servico_telefone                            7032 non-null   int64
 8   fatura_digital                              7032 non-null   int64
 9   cobranca_mensal                             7032 non-null   float64
 10  cobranca_total                              7032 non-null   float64
 11  varias_linhas_sem_servico_telefone          7032 non-null   bool
 12  varias_linhas_sim                           7032 non-null   bool
 13  internet_fibra_optica                       7032 non-null   bool
 14  internet_sem_servico                        7032 non-null   bool
 15  seguranca_online_sem_servico_internet       7032 non-null   bool
 16  seguranca_online_sim                        7032 non-null   bool
 17  backup_online_sem_servico_internet          7032 non-null   bool
 18  backup_online_sim                           7032 non-null   bool
 19  protecao_dispositivo_sem_servico_internet   7032 non-null   bool
 20  protecao_dispositivo_sim                    7032 non-null   bool
 21  suporte_tecnico_sem_servico_internet        7032 non-null   bool
 22  suporte_tecnico_sim                         7032 non-null   bool
 23  tv_streaming_sem_servico_internet           7032 non-null   bool
 24  tv_streaming_sim                            7032 non-null   bool
 25  filmes_streaming_sem_servico_internet       7032 non-null   bool
 26  filmes_streaming_sim                        7032 non-null   bool
 27  contrato_um_ano                             7032 non-null   bool
 28  contrato_dois_anos                          7032 non-null   bool
 29  metodo_pagamento_cartao_credito_automatico  7032 non-null   bool
 30  metodo_pagamento_cheque_eletronico          7032 non-null   bool
 31  metodo_pagamento_cheque_pelo_correio        7032 non-null   bool
dtypes: bool(21), float64(2), int64(8), object(1)
memory usage: 803.5+ KB

### 6. Criando Cópia `df_ml` (Cópia para Análise)

In [24]:
# Cria uma cópia do DataFrame 'df_ml' para ser usado na análise e visualização com valores revertidos
df_analise = df_ml.copy()

print("df_analise criado como cópia de df_ml.")

df_analise criado como cópia de df_ml.

### 7. Revertendo Valores Binários para Texto (no `df_analise`)

In [25]:
# Mapeamento para reverter 0/1 para texto traduzido
reverse_binary_mapping = {
    0: 'Não',
    1: 'Sim'
}

reverse_gender_mapping = {
    0: 'Feminino',
    1: 'Masculino'
}

# Lista de colunas binarizadas para reverter
columns_to_revert = [
    'churn',
    'tem_parceiro',
    'tem_dependentes',
    'servico_telefone',
    'fatura_digital'
]

for col in columns_to_revert:
    if col in df_analise.columns:
        df_analise[col] = df_analise[col].map(reverse_binary_mapping)
        print(f"Coluna '{col}' revertida. Valores únicos: {df_analise[col].unique()}")

# Revertendo a coluna de gênero
df_analise['genero_cliente'] = df_analise['genero_cliente'].map(reverse_gender_mapping)
print(f"Coluna 'genero_cliente' revertida. Valores únicos: {df_analise['genero_cliente'].unique()}")


# Para as colunas de One-Hot Encoding (que são várias), vamos criar um mapeamento mais complexo ou uma lógica específica
# Isso é mais trabalhoso, pois cada conjunto de OHE representa uma coluna original.
# Por exemplo, para 'internet_fibra_optica', 'internet_sem_servico', a ausência de 1 nas duas implica 'DSL'.
# Para simplicidade de visualização, você pode focar em converter apenas as colunas binarizadas 'padrão' e o gênero.

print("\nValores de algumas colunas após a reversão:")
display(df_analise[['churn', 'genero_cliente', 'tem_parceiro', 'fatura_digital']].head())

print("\nVerificando os tipos de dados após a reversão (algumas colunas voltarão a ser object):")
df_analise.info()

Coluna 'churn' revertida. Valores únicos: ['Não' 'Sim']
Coluna 'tem_parceiro' revertida. Valores únicos: ['Sim' 'Não']
Coluna 'tem_dependentes' revertida. Valores únicos: ['Sim' 'Não']
Coluna 'servico_telefone' revertida. Valores únicos: ['Sim' 'Não']
Coluna 'fatura_digital' revertida. Valores únicos: ['Sim' 'Não']
Coluna 'genero_cliente' revertida. Valores únicos: ['Feminino' 'Masculino']

Valores de algumas colunas após a reversão:

  churn genero_cliente tem_parceiro fatura_digital
0   Não       Feminino          Sim            Sim
1   Não      Masculino          Não            Não
2   Sim      Masculino          Não            Sim
3   Sim      Masculino          Sim            Sim
4   Sim       Feminino          Sim            Sim

Verificando os tipos de dados após a reversão (algumas colunas voltarão a ser object):
<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7266
Data columns (total 32 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   id_cliente                                  7032 non-null   object
 1   churn                                       7032 non-null   object
 2   genero_cliente                              7032 non-null   object
 3   cliente_senior                              7032 non-null   int64
 4   tem_parceiro                                7032 non-null   object
 5   tem_dependentes                             7032 non-null   object
 6   meses_servico                               7032 non-null   int64
 7   servico_telefone                            7032 non-null   object
 8   fatura_digital                              7032 non-null   object
 9   cobranca_mensal                             7032 non-null   float64
 10  cobranca_total                              7032 non-null   float64
 11  varias_linhas_sem_servico_telefone          7032 non-null   bool
 12  varias_linhas_sim                           7032 non-null   bool
 13  internet_fibra_optica                       7032 non-null   bool
 14  internet_sem_servico                        7032 non-null   bool
 15  seguranca_online_sem_servico_internet       7032 non-null   bool
 16  seguranca_online_sim                        7032 non-null   bool
 17  backup_online_sem_servico_internet          7032 non-null   bool
 18  backup_online_sim                           7032 non-null   bool
 19  protecao_dispositivo_sem_servico_internet   7032 non-null   bool
 20  protecao_dispositivo_sim                    7032 non-null   bool
 21  suporte_tecnico_sem_servico_internet        7032 non-null   bool
 22  suporte_tecnico_sim                         7032 non-null   bool
 23  tv_streaming_sem_servico_internet           7032 non-null   bool
 24  tv_streaming_sim                            7032 non-null   bool
 25  filmes_streaming_sem_servico_internet       7032 non-null   bool
 26  filmes_streaming_sim                        7032 non-null   bool
 27  contrato_um_ano                             7032 non-null   bool
 28  contrato_dois_anos                          7032 non-null   bool
 29  metodo_pagamento_cartao_credito_automatico  7032 non-null   bool
 30  metodo_pagamento_cheque_eletronico          7032 non-null   bool
 31  metodo_pagamento_cheque_pelo_correio        7032 non-null   bool
dtypes: bool(21), float64(2), int64(2), object(7)
memory usage: 803.5+ KB

#📊 Carga e análise

#📄Relatorio Final